<form class="main-form" action="">
    <div class="firstname-wrapper">
        <label for="firstname">First Name</label>
        <input type="text" id="firstname" class="firstname">
    </div>
    <div class="secondname-wrapper">
        <label for="secondname">Second Name</label>
        <input type="text" id="secondname" class="secondname">
    </div>
    <button type="button" class="button-success">Отправить</button>
</form>